# Generated by Django 4.2.11 on 2024-04-23 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardList',
            fields=[
                ('card_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('issuer', models.CharField(max_length=255)),
                ('travel_reward', models.FloatField(default=0)),
                ('dining_reward', models.FloatField(default=0)),
                ('grocery_reward', models.FloatField(default=0)),
                ('shopping_reward', models.FloatField(default=0)),
                ('gas_reward', models.FloatField(default=0)),
                ('entertainment_reward', models.FloatField(default=0)),
                ('other_reward', models.FloatField(default=0)),
                ('annual_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpendingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('travel_amount', models.IntegerField()),
                ('dining_amount', models.IntegerField()),
                ('grocery_amount', models.IntegerField()),
                ('gas_amount', models.IntegerField()),
                ('entertainment_amount', models.IntegerField()),
                ('other_amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithms.userlist')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('spending_category', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithms.userlist')),
            ],
        ),
        migrations.CreateModel(
            name='CardRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_rec', models.DateField()),
                ('card_name_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_name_1', to='algorithms.cardlist')),
                ('card_name_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_name_2', to='algorithms.cardlist')),
                ('card_name_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_name_3', to='algorithms.cardlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithms.userlist')),
            ],
        ),
        migrations.CreateModel(
            name='OwnedCards',
            fields=[
                ('card_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='algorithms.cardlist')),
                ('travel_reward', models.IntegerField()),
                ('dining_reward', models.IntegerField()),
                ('grocery_reward', models.IntegerField()),
                ('gas_reward', models.IntegerField()),
                ('entertainment_reward', models.IntegerField()),
                ('other_reward', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithms.userlist')),
            ],
        ),
    ]
