# Generated by Django 5.0.2 on 2024-03-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, unique=True)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='', max_length=20, unique=True)),
            ],
        ),
    ]
