# Generated by Django 5.0.2 on 2024-05-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_alter_cardrecommendations_date_of_rec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlist',
            name='creditscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardlist',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cardlist',
            name='long_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cardlist',
            name='reward_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cardlist',
            name='website',
            field=models.CharField(default='', max_length=255),
        ),
    ]
