# Generated by Django 5.0.4 on 2024-05-05 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_alter_cardrecommendations_date_of_rec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
