# Generated by Django 5.0.2 on 2024-05-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_cardlist_creditscore_cardlist_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlist',
            name='creditscore',
            field=models.CharField(default='', max_length=255),
        ),
    ]
