# Generated by Django 5.0.2 on 2024-05-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0004_alter_cardlist_creditscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_amount', models.IntegerField()),
                ('dining_amount', models.IntegerField()),
                ('grocery_amount', models.IntegerField()),
                ('gas_amount', models.IntegerField()),
                ('entertainment_amount', models.IntegerField()),
                ('other_amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithms.userlist')),
            ],
        ),
    ]
